project_name: fadian-go

before:
  hooks:
    - go mod tidy

builds:
  - id: fadian-go
    main: .
    binary: fadian-go
    env:
      - CGO_ENABLED=0
      - >-
        {{- if eq .Os "darwin" }}
          {{- if eq .Arch "amd64"}}CC=o64-clang{{- end }}
          {{- if eq .Arch "arm64"}}CC=aarch64-apple-darwin20.2-clang{{- end }}
        {{- end }}
        {{- if eq .Os "windows" }}
          {{- if eq .Arch "amd64" }}CC=x86_64-w64-mingw32-gcc{{- end }}
        {{- end }}
    ldflags:
      - -s -w -X main.version={{ .Version }} -X main.commit={{ .Commit }}
    goos:
      - "linux"
      - "windows"
      - "darwin"
    goarch:
      - "amd64"
      - "arm64"

universal_binaries:
  - id: fadian-go

signs:
  - artifacts: checksum
    args: ["--batch", "-u", "{{ .Env.GPG_FINGERPRINT }}", "--output", "${signature}", "--detach-sign", "${artifact}"]

archives:
  - format: tar.gz
    # this name template makes the OS and Arch compatible with the results of uname.
    name_template: >-
      {{ .ProjectName }}_
      {{- title .Os }}_
      {{- if eq .Arch "amd64" }}x86_64
      {{- else if eq .Arch "386" }}i386
      {{- else }}{{ .Arch }}{{ end }}
      {{- if .Arm }}v{{ .Arm }}{{ end }}
    # use zip for windows archives
    format_overrides:
      - goos: windows
        format: zip
    files:
      - src: data/*
        dst: data
        info:
          owner: root
          group: root
          mtime: "{{ .CommitDate }}"
          mode: 0644

release:
  github:
    owner: afadian
    name: fadian-go
  draft: true
  replace_existing_draft: true
  prerelease: auto
  mode: append

checksum:
  name_template: 'checksums.txt'

snapshot:
  name_template: "{{ incpatch .Version }}-snapshot"

changelog:
  sort: asc
  filters:
    exclude:
      - '^doc:'
      - '^test:'
